#!/bin/sh -e
# Automatically added by dh_installdocs
if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/libgnewt0.06 ]; then
	rm -f /usr/doc/libgnewt0.06
fi
# End automatically added section
